apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftinstances.jali-clarke.ca
spec:
  group: jali-clarke.ca
  scope: Namespaced
  names:
    plural: minecraftinstances
    singular: minecraftinstance
    kind: MinecraftInstance
    shortNames:
    - mi
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              minecraftVersion:
                type: string
                pattern: "^\d+\(.\d+){2}$"
              nodePortService:
                type: object
                properties:
                  serviceName:
                    type: string
                  nodePort:
                    type: integer
